dataset: 'scannet'
meshing:
  resolution: 0.02 #cm # Increase this number to speed up meshing algorithm
  eval_rec: False
tracking:
  ignore_edge_W: 75
  ignore_edge_H: 75
  lr_T: 0.0005
  lr_R: 0.0025
  pixels: 2000
  iters: 30
  vis_freq: 100
  vis_inside_freq: 25
mapping:
  pixels: 4000
  iters: 30
  max_drift: 3 #just for test
  vis_freq: 100
  vis_inside_freq: 30
  n_pixels: 0.05
  w_smooth: 0.001
cam: 
  H: 480 
  W: 640
  fx: 577.590698
  fy: 578.729797
  cx: 318.905426
  cy: 242.683609
  png_depth_scale: 1000. #for depth image in png format
  crop_edge: 10
rendering:
  n_stratified: 48
  n_importance: 8
  learnable_beta: True
pos:
  enc: 'OneBlob'
  n_bins: 16
decoder:
  geo_feat_dim: 15
  hidden_dim: 32
  num_layers: 2
  num_layers_color: 2
  hidden_dim_color: 32
  tcnn_network: False
data:
  trainskip: 1
  sc_factor: 1
  downsample: 1
  translation: 0
  num_workers: 4
training: #for smoothness loss
  trunc: 0.1
  smooth_vox: 0.1
  smooth_margin: 0.05
  smooth_pts: 64
grid:
  tcnn_encoding: True
