inherit_from: /data0/wjy/sgl/ESLAM-main-list/configs/ScanNet/scannet.yaml
mapping:
  bound: [[0.3,9.9],[-1.0,8.0],[-1.0,3.8]]
  marching_cubes_bound: [[0.3,9.9],[-1.0,8.0],[-1.0,3.8]]
  max_drift: 4 #just for test
data:
  input_folder: /data0/wjy/ESLAM/Datasets/scannet/scene0207_00
  #input_folder: /data0/dataset/ScanNet/scans/scene0207_00
  #output: output/scannet/scans/scene0207_00_max3_gloc
  output: /data0/wjy/sgl/nice-slam/output/scannet/scans/scene_0207_00

