inherit_from: configs/ScanNet/scannet.yaml
mapping:
  bound: [[-0.2,9.8],[-1.0,8.5],[-1.0,3.4]]
  marching_cubes_bound: [[-0.2,9.8],[-1.0,8.5],[-1.0,3.4]]
  max_drift: 4 #just for test
data:
  input_folder: /data0/dataset/ScanNet/scans/scene0169_00
  output: output/scannet/scans/scene0169_00_smooth_max4