inherit_from: configs/Replica/replica.yaml
mapping:
  bound: [[-4.3,5.5],[-4.1,5.0],[-3.5,4.2]]
  marching_cubes_bound: [[-4.3,5.5],[-4.1,5.0],[-3.5,4.2]]
data:
  input_folder: /data0/wjy/ESLAM/Datasets/Replica/office1
  output: output/Replica/office1
  trainskip: 1

