dataset: 'replica'
meshing:
  resolution: 0.01 #cm # Increase this number to speed up meshing algorithm
  eval_rec: True
tracking:
  ignore_edge_W: 75
  ignore_edge_H: 75
  lr_T: 0.002
  lr_R: 0.001
  pixels: 2000
  iters: 8
  vis_freq: 50
  vis_inside_freq: 25
  #iters: 10
mapping:
  #every_frame: 5
  every_frame: 4
  pixels: 4000
  iters: 15
  lr_embed: 0.01
  lr_decoder: 0.01
  #iters: 60
  vis_freq: 50
  vis_inside_freq: 30
  w_sdf_fs: 5
  w_sdf_center: 200
  w_sdf_tail: 30
  w_depth: 0.1
  w_color: 5
  w_smooth: 0.000001
  n_pixels: 0.05
  max_drift: 10 #just for test
  #mesh_freq: 1500 #just for test
cam:
  H: 680
  W: 1200
  fx: 600.0
  fy: 600.0
  cx: 599.5
  cy: 339.5
  png_depth_scale: 6553.5 #for depth image in png format
  crop_edge: 0
rendering:
  n_stratified: 32
  n_importance: 8
  learnable_beta: True
pos:
  enc: 'OneBlob'
  n_bins: 16
decoder:
  geo_feat_dim: 15
  hidden_dim: 32
  num_layers: 2
  num_layers_color: 2
  hidden_dim_color: 32
  tcnn_network: False
data:
  sc_factor: 1
  downsample: 1
  translation: 0
  num_workers: 4

training:
  trunc: 0.06
  smooth_pts: 32
  smooth_vox: 0.1
  smooth_margin: 0.05
grid:
  tcnn_encoding: True
