inherit_from: /data0/sgl/ESLAM-main/configs/7Scenes/7Scenes.yaml
mapping:
  bound: [[-8., 8.], [-8., 8.], [-8., 8.]]
  marching_cubes_bound: [[-8., 8.], [-8., 8.], [-8., 8.]]
data:
  input_folder: /data0/dataset/7scenes/chess/seq-01
  output: /data0/sgl/ESLAM-main/output/7-Scenes/chess/seq-01
  trainskip: 1
